name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
         node-version: 17.x
      - run: npm install
      
      - run: npm run build --if-present

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: heenasingh1011/helloworld_react@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Testing-react
          environment_name: Testing-react-env
          version_label: 12345
          region: ap-south-1
          deployment_package: deploy.zip


